### ISSUE TITLE
Gamecube.begin(2); Fails

### ISSUE THREAD

**Issue by Ivoah** [NicoHood/Nintendo#1]
I have the gamecube controller plugged into my breadboard and Arduino Micro: ![gc](https://cloud.githubusercontent.com/assets/2159017/3750574/7ca5fd22-17f7-11e4-976e-a8a4aa76485c.png)

This setup worked using brownan's N64 to Gamecube program. The resistor in the image should be 1KΩ

**Comment by NicoHood** [comment]
Can you please try again with the current beta version 1.1?
https://github.com/NicoHood/Nintendo/tree/beta

Should work with the newer IDE 1.6 as well.
