### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Dreamer68** [NicoHood/Nintendo#10]
Hello, I have a problem when I try to compile the program ‘Gamecube_USB_HID.ino’:

"
Arduino : 1.6.12 (Windows 10), Carte : "HoodLoader2 16u2, HoodLoader2 Uno"

...\Arduino\libraries\Nintendo-master\src\Gamecube_N64.c: In function 'gc_n64_send_get':

...\Arduino\libraries\Nintendo-master\src\Gamecube_N64.c:195:5: error: can't find a register in class 'POINTER_REGS' while reloading 'asm'

     asm volatile (

     ^

..\Arduino\libraries\Nintendo-master\src\Gamecube_N64.c:195:5: error: 'asm' operand has impossible constraints

lto-wrapper: ..\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-gcc returned 1 exit status

../appdata/local/arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.3-arduino2/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
"

Can you help me please?

**Comment by NicoHood** [comment]
You are using an old version of the library. How did you download it? Please update. Also update your IDE.

**Comment by Dreamer68** [comment]
Yet I downloaded it yesterday here:
Https://github.com/NicoHood/Nintendo

**Comment by NicoHood** [comment]
Please use the latest IDE and tell me the sketch you try to compile.

**Comment by Dreamer68** [comment]
I tried with the latest version, but there is the same error.

I try to compile, ‘Gamecube_USB_HID.ino’

**Comment by NicoHood** [comment]
Fixed in the latest version. Thanks for your report!
Please close this issue if the new version works for you.

**Comment by Dreamer68** [comment]
Thanks.
I managed to compile it. thank you very much :)
