### ISSUE TITLE
Issue running on Arduino Uno Atmega328

### ISSUE THREAD

**Issue by hallcristobal** [NicoHood/Nintendo#17]
Having issues running on Arduino Uno, Tried the Example project "GamecubeConsole" with wires arc'd except for the data wire, controller end put into pin 7 and console wire put into pin 8. 
All I get from serial is "Error reading Gamecube Controller", 

Any ideas?

**Comment by NicoHood** [comment]
You possibly wired it wrong.

**Comment by hallcristobal** [comment]
My apologies, how should they be connected? Is there more that needs to be connected than just the data wires to the arduino?

**Comment by NicoHood** [comment]
https://github.com/NicoHood/Nintendo/wiki/Gamecube

Read it carefully and try again. If it does not work, please ask in the arduino forum or IRC.
