### ISSUE TITLE
GC rumble question

### ISSUE THREAD

**Issue by clbr** [NicoHood/Nintendo#18]
Your GC page mentions the rumble motor drew 30 mA. This is quite low, and I can't find any other sources online with measurements. Other consoles' controllers seem to draw more.

So just asking to be sure, is it 30 mA and not 300 mA for example?

**Comment by NicoHood** [comment]
I have no idea. I think i measured it with my multimeter, but that could be inaccurate. You might want to find it out yourself.

**Comment by clbr** [comment]
I got to measuring three GC controllers' 5V lines when rumbling. Results:
Original Nintendo: 36 mA
Smash Ultimate (released 2018 Dec): 32 mA
3rd party, GameStop brand: 40 mA

So they indeed draw so little.

**Comment by NicoHood** [comment]
I've added this issue to the docs as a link.
