### ISSUE TITLE
GameCube USB HID D-Pad stuck in last direction pressed

### ISSUE THREAD

**Issue by xperia64** [NicoHood/Nintendo#23]
When using the GameCube controller USB HID example, the PC D-Pad hat seems to get stuck in the last direction it was pressed.

The D-Pad doesn't seem to get stuck when using the serial console controller printing example.

**Comment by NicoHood** [comment]
Did you manage to solve the issue?

**Comment by xperia64** [comment]
Ultimately no, but I ended up switching to a commercial USB adapter.

**Comment by NicoHood** [comment]
Alright, I will close this issue then.
