### ISSUE TITLE
 when send 1 for L or R not work

### ISSUE THREAD

**Issue by asa181192** [NicoHood/Nintendo#27]
why if i send 1 to the L or R button it doesnt work .

`
data.report.r= 1;`
`
       GamecubeConsole1.write(data);`

i tested with other buttons like A or B and Y and works normally but for L and R it doesnt work. im testing with super smash bros ultimate and the cpu its suposed to hold the shield .

**Comment by NicoHood** [comment]
Ouf... I am not sure anymore, but what happens if you set left and right buttons to 255?
https://github.com/NicoHood/Nintendo/blob/master/src/Gamecube.h#L87
