### ISSUE TITLE
Is just only for the arduino Uno?

### ISSUE THREAD

**Issue by lipe-dev** [NicoHood/Nintendo#53]
Sorry if it's a stupid question, I'm a noob at this stuff.
Is this only for the Arduino uno or can I use something like a Pro Micro with it?

**Comment by Skuzee** [comment]
I've done a project using this on a sparkfun pro micro and it works great (atmega32u4). The main requirement for a board is it needs to be a 16MHz AVR processor because the timing of the communication is hard coded in assembly.

**Comment by lipe-dev** [comment]
@Skuzee thanks friend!
